### ISSUE TITLE
Issues when old scenario test results are not cleared

### ISSUE THREAD

**Issue by rawadelkontar** [urbanopt/urbanopt-scenario-gem#25]

**Comment by macumber** [comment]
Thanks @rawadelkontar, can you give the steps to reproduce?  It would be even better if you can write a failing unit test that demonstrates the error.

**Comment by rawadelkontar** [comment]
> Thanks @rawadelkontar, can you give the steps to reproduce? It would be even better if you can write a failing unit test that demonstrates the error.

There is no error. The issue is that when you set clear_results to false the reporting measure file will not run (use old stored results instead).  So every time you do any change in the reporting measure you have to set_clear results to true. Also when the measure file breaks  the scenario test still runs with no errors; this is a bit confusing.  The test in the urbanopt_scenario_spec that can run a scenario should also considers failures in the measure file and any updates.
