### ISSUE TITLE
Add folder for mapper csv files

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-scenario-gem#56]
don't save mapper CSV files in the root.  make a dedicated folder to hold them.

**Comment by vtnate** [comment]
I think you are referring to the example geojson project here? If so, this has been completed. https://github.com/urbanopt/urbanopt-example-geojson-project/tree/develop/mappers. With the advent of the CLI this doesn't need to matter, as these files are simply downloaded and could just as easily be stored in the CLI repo.
